### ISSUE TITLE
Szene 3 Basics (Hintergrund, Pfeile und Charaktere)

### ISSUE THREAD

**Issue by cmd-johnson** [ShaatsSucher/antonius-phaser#122]
- [x] Klasse für Szene erstellen
- [x] Szenenklasse im Preloader registrieren
- [x] Hintergrund für die Szene festlegen #131
- [x] Charakterklassen erstellen
    - [x] Eule #92
- [x] Charactere in der Szene platzieren
    - [x] Eule
    - [x] Antonius
- [x] Pfeile für Wechsel zu anderen Szenen hinzufügen
    - [x] Nach links zu Stirn (Szene 2) #121 
    - [x] Nach unten zu Frau + Baum (Szene 7) #126
