### ISSUE TITLE
Szene 7 Basics (Hintergrund, Pfeile und Charaktere)

### ISSUE THREAD

**Issue by cmd-johnson** [ShaatsSucher/antonius-phaser#126]
- [x] Klasse für Szene erstellen
- [x] Szenenklasse im Preloader registrieren
- [x] Hintergrund für die Szene festlegen #132
- [x] Charakterklassen erstellen
    - [x] Frau #93
    - [x] Baum #94
    - [x] Ziege #42 #77 #43
- [x] Charactere in der Szene platzieren
    - [x] Frau
    - [x] Baum
    - [x] Ziege
    - [x] Antonius
- [x] Pfeile für Wechsel zu anderen Szenen hinzufügen
    - [x] Nach oben auf die Baumkrone (Szene 3) #122 
    - [x] Nach rechts ins Bauminnere (Szene 8) #127
    - [x] Nach unten zu Bremer Stadtmusikanten (Szene 11) #130
    - [x] Nach links zu Meckie + Barde (Szene 6) #125
