### ISSUE TITLE
Szene 10 Basics (Hintergrund, Pfeile und Charaktere)

### ISSUE THREAD

**Issue by cmd-johnson** [ShaatsSucher/antonius-phaser#129]
- [x] Klasse für Szene erstellen
- [x] Szenenklasse im Preloader registrieren
- [x] Hintergrund für die Szene festlegen #103 
- [x] Charakterklassen erstellen
    - [x] Köche #99
    - [x] Eierfrau #98 
- [x] Charactere in der Szene platzieren
    - [x] Köche
    - [x] Eierfrau
    - [x] Antonius
- [x] Pfeile für Wechsel zu anderen Szenen hinzufügen
    - [x] Nach oben zu Meckie + Barde (Szene 6) #125
    - [x] Nach rechts zu Bremer Stadtmusikanten (Szene 11) #130 
    - [x] Nach links zu Fisch (Szene 9)  #128
