### ISSUE TITLE
Szene 11 Basics (Hintergrund, Pfeile und Charaktere)

### ISSUE THREAD

**Issue by cmd-johnson** [ShaatsSucher/antonius-phaser#130]
- [x] Klasse für Szene erstellen
- [x] Szenenklasse im Preloader registrieren
- [x] Hintergrund für die Szene festlegen #104 
- [x] Charakterklassen erstellen
    - [x] Bremer Stadtmusikanten #100
    - [x] Feststeckender Schwan #101
    - [x] Schlangen #102
- [x] Charactere in der Szene platzieren
    - [x] Bremer Stadtmusikanten
    - [x] Feststeckender Schwan
    - [x] Schlangen
    - [x] Antonius
- [x] Pfeile für Wechsel zu anderen Szenen hinzufügen
    - [x] Nach zu Frau + Baum (Szene 7) #126 
    - [x] Nach links zu Köchen (Szene 10) #129
